#!/usr/bin/env bash
# Build and run the Dirtbag sim core's standalone test harness with plain g++.
# The same .cpp files compile inside the Unreal module — this harness is what
# keeps the sim honest before (and after) the editor exists.
set -euo pipefail
cd "$(dirname "$0")"

mkdir -p ../build
g++ -std=c++17 -O2 -Wall -Wextra -Werror \
    DirtbagRng.cpp DirtbagCore.cpp DirtbagSession.cpp DirtbagSessionLoop.cpp \
    DirtbagDay.cpp DirtbagSave.cpp DirtbagConditions.cpp DirtbagCrag.cpp DirtbagFirstAscent.cpp DirtbagPartner.cpp DirtbagDog.cpp DirtbagGear.cpp DirtbagVan.cpp DirtbagJobs.cpp DirtbagFactions.cpp DirtbagCrew.cpp DirtbagDreams.cpp DirtbagCampfire.cpp DirtbagZones.cpp DirtbagCharacter.cpp DirtbagRival.cpp DirtbagComp.cpp DirtbagTeam.cpp DirtbagWorldStage.cpp DirtbagLeague.cpp DirtbagMedical.cpp DirtbagAilments.cpp DirtbagBodyContext.cpp DirtbagCraft.cpp DirtbagTown.cpp DirtbagKit.cpp DirtbagBody.cpp DirtbagAge.cpp DirtbagSport.cpp DirtbagTrad.cpp DirtbagHabits.cpp DirtbagNarrator.cpp DirtbagLife.cpp DirtbagLocals.cpp DirtbagGym.cpp DirtbagGymTown.cpp DirtbagGymFloor.cpp DirtbagGymLeague.cpp DirtbagSpeed.cpp DirtbagYouth.cpp DirtbagLiving.cpp DirtbagBivy.cpp DirtbagLegacy.cpp DirtbagSponsor.cpp DirtbagEthics.cpp \
    tests/test_main.cpp \
    -o ../build/sim_tests

../build/sim_tests

# Unity-build check. UBT concatenates the module's translation units into one
# file, so two .cpp files that each define the same helper in an anonymous
# namespace collide there — while compiling perfectly here, where every file
# is its own unit. That exact mistake (a second Clamp01) broke a build, and
# nothing in the container could see it. This compiles every sim unit as one
# translation unit, the way Unreal will.
UNITY=../build/unity_check.cpp
{
  echo "// Generated by run-tests.sh — simulates UBT's unity build."
  for f in *.cpp; do echo "#include \"$f\""; done
} > "$UNITY"
g++ -std=c++17 -Wall -Wextra -Werror -fsyntax-only -I. "$UNITY"
echo "OK  unity build clean ($(ls *.cpp | wc -l | tr -d ' ') sim units as one TU)"

# **And again at the standard Unreal actually builds at, with a second
# compiler.** This harness has always been one compiler at one language
# version, and the engine module is neither: UE 5.8 compiles at **C++20**,
# on MSVC, and nothing in this container is either of those things.
#
# Two cheap approximations of the gap. C++20 catches the rules that changed
# under our feet -- aggregate initialisation, comparison operators, implicit
# lambda captures of `this`. A second front end catches what one front end
# happens to tolerate, which is most of what "it built here and not there"
# ever means.
#
# Syntax-only, so both together cost about as much as one -O2 build. Neither
# is MSVC and neither is UHT; the point is to shrink the set of things only
# Evan's PC can find, not to pretend it is empty.
for STD in c++17 c++20; do
  g++ -std=$STD -Wall -Wextra -Wshadow -Werror -fsyntax-only -I. "$UNITY"
done
echo "OK  and at C++20, the standard Unreal builds at"

if command -v clang++ >/dev/null 2>&1; then
  for STD in c++17 c++20; do
    clang++ -std=$STD -Wall -Wextra -Wshadow -Werror -fsyntax-only -I. "$UNITY"
  done
  echo "OK  and under clang, which is a different front end with different opinions"
else
  # Said out loud rather than skipped in silence. A check that quietly stops
  # running is worse than one that was never written, because the green tick
  # goes on meaning something it no longer means.
  echo "--  clang++ not installed; that half of the front-end check did not run"
fi
