#!/usr/bin/env bash
# Build and run the Dirtbag sim core's standalone test harness with plain g++.
# The same .cpp files compile inside the Unreal module — this harness is what
# keeps the sim honest before (and after) the editor exists.
set -euo pipefail
cd "$(dirname "$0")"

mkdir -p ../build
g++ -std=c++17 -O2 -Wall -Wextra -Werror \
    DirtbagRng.cpp DirtbagCore.cpp DirtbagSession.cpp DirtbagSessionLoop.cpp \
    DirtbagDay.cpp DirtbagSave.cpp DirtbagConditions.cpp DirtbagCrag.cpp DirtbagFirstAscent.cpp DirtbagPartner.cpp DirtbagDog.cpp DirtbagGear.cpp DirtbagVan.cpp DirtbagJobs.cpp DirtbagFactions.cpp DirtbagCrew.cpp DirtbagDreams.cpp DirtbagCampfire.cpp DirtbagTown.cpp DirtbagKit.cpp DirtbagBody.cpp DirtbagAge.cpp DirtbagSport.cpp DirtbagLegacy.cpp DirtbagSponsor.cpp DirtbagEthics.cpp \
    tests/test_main.cpp \
    -o ../build/sim_tests

../build/sim_tests

# Unity-build check. UBT concatenates the module's translation units into one
# file, so two .cpp files that each define the same helper in an anonymous
# namespace collide there — while compiling perfectly here, where every file
# is its own unit. That exact mistake (a second Clamp01) broke a build, and
# nothing in the container could see it. This compiles every sim unit as one
# translation unit, the way Unreal will.
UNITY=../build/unity_check.cpp
{
  echo "// Generated by run-tests.sh — simulates UBT's unity build."
  for f in *.cpp; do echo "#include \"$f\""; done
} > "$UNITY"
g++ -std=c++17 -Wall -Wextra -Werror -fsyntax-only -I. "$UNITY"
echo "OK  unity build clean ($(ls *.cpp | wc -l | tr -d ' ') sim units as one TU)"
